In [17]:
import pandas as pd

file_path = '/Users/madhusreekalluri/Desktop/customer behaviour portfolio project/customer_shopping_behavior.csv'
df = pd.read_csv(file_path)
display(df.head())

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [19]:
display(df.describe(include='all'))

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [20]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [21]:
df['Category'].unique()

array(['Clothing', 'Footwear', 'Outerwear', 'Accessories'], dtype=object)

In [22]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [23]:
df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')
display(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [24]:
print("Unique values in 'discount_applied':")
display(df['discount_applied'].unique())

print("\nUnique values in 'promo_code_used':")
display(df['promo_code_used'].unique())

Unique values in 'discount_applied':

array(['Yes', 'No'], dtype=object)

Unique values in 'promo_code_used':

array(['Yes', 'No'], dtype=object)

In [25]:
frequency_table = pd.crosstab(df['discount_applied'], df['promo_code_used'])
display(frequency_table)

promo_code_used     No   Yes
discount_applied
No                2223     0
Yes                  0  1677

In [26]:
df.drop('promo_code_used', axis=1, inplace=True)
print("Column 'promo_code_used' deleted. Updated columns:")
display(df.columns)

Column 'promo_code_used' deleted. Updated columns:

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

## Create Age Groups

In [27]:
min_age = df['age'].min()
max_age = df['age'].max()

print(f"Minimum age: {min_age}")
print(f"Maximum age: {max_age}")

Minimum age: 18
Maximum age: 70

In [28]:
bins = [18, 26, 46, 61, 71]
labels = ['Young Adult', 'Adult', 'Mid Age', 'Senior Citizen']

df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)

print("New 'age_group' column created.")

New 'age_group' column created.

In [29]:
display(df['age_group'].value_counts())

age_group
Adult             1471
Mid Age           1135
Senior Citizen     723
Young Adult        571
Name: count, dtype: int64

In [30]:
frequency_mapping = {
    'Daily': 1,
    'Weekly': 7,
    'Bi-Weekly': 14,
    'Fortnightly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Every 3 months': 90,
    'Annually': 365
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

print("Value counts for the new 'purchase_frequency_days' column:")
print(df['purchase_frequency_days'].value_counts())
print("\nFirst 5 rows with 'frequency_of_purchases' and 'purchase_frequency_days' columns:")
print(df[['frequency_of_purchases', 'purchase_frequency_days']].head())

Value counts for the new 'purchase_frequency_days' column:
purchase_frequency_days
14.0     1089
365.0     572
90.0      563
30.0      553
7.0       539
Name: count, dtype: int64

First 5 rows with 'frequency_of_purchases' and 'purchase_frequency_days' columns:
  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                     14.0
1            Fortnightly                     14.0
2                 Weekly                      7.0
3                 Weekly                      7.0
4               Annually                    365.0

In [31]:
df['frequency_of_purchases_days'] = df['frequency_of_purchases'].map(frequency_mapping)
print("Converted 'frequency_of_purchases' to numerical days.")
display(df.head())
df.info()

Converted 'frequency_of_purchases' to numerical days.

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days,frequency_of_purchases_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Mid Age,14.0,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Mid Age,7.0,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Adult,365.0,365.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  3900 non-null   int64
 1   age                          3900 non-null   int64
 2   gender                       3900 non-null   object
 3   item_purchased               3900 non-null   object
 4   category                     3900 non-null   object
 5   purchase_amount_(usd)        3900 non-null   int64
 6   location                     3900 non-null   object
 7   size                         3900 non-null   object
 8   color                        3900 non-null   object
 9   season                       3900 non-null   object
 10  review_rating                3900 non-null   float64
 11  subscription_status          3900 non-null   object
 12  shipping_type                3900 non-null   object
 13  discount_applied             3900 non-null   object
 14  previous_purchases           3900 non-null   int64
 15  payment_method               3900 non-null   object
 16  frequency_of_purchases       3900 non-null   object
 17  age_group                    3900 non-null   category
 18  purchase_frequency_days      3316 non-null   float64
 19  frequency_of_purchases_days  3316 non-null   float64
dtypes: category(1), float64(3), int64(4), object(12)
memory usage: 583.0+ KB

In [32]:
print("Unique values in 'frequency_of_purchases':")
display(df['frequency_of_purchases'].unique())
print("\nData type of 'frequency_of_purchases':")
display(df['frequency_of_purchases'].dtype)

Unique values in 'frequency_of_purchases':

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

Data type of 'frequency_of_purchases':

dtype('O')

In [33]:
import pandas as pd

file_path = '/Users/madhusreekalluri/Desktop/customer behaviour portfolio project/customer_shopping_behavior.csv'
df = pd.read_csv(file_path)
display(df.head())

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [34]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [35]:
df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')
display(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [36]:
df.drop('promo_code_used', axis=1, inplace=True)
print("Column 'promo_code_used' deleted. Updated columns:")
display(df.columns)

Column 'promo_code_used' deleted. Updated columns:

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [37]:
bins = [18, 26, 46, 61, 71]
labels = ['Young Adult', 'Adult', 'Mid Age', 'Senior Citizen']

df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)

print("New 'age_group' column created.")
display(df['age_group'].value_counts())

New 'age_group' column created.

age_group
Adult             1471
Mid Age           1135
Senior Citizen     723
Young Adult        571
Name: count, dtype: int64

In [38]:
df['frequency_of_purchases_days'] = df['frequency_of_purchases'].map(frequency_mapping)
print("Converted 'frequency_of_purchases' to numerical days.")
display(df.head())
df.info()

Converted 'frequency_of_purchases' to numerical days.

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,frequency_of_purchases_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Mid Age,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Mid Age,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Adult,365.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  3900 non-null   int64
 1   age                          3900 non-null   int64
 2   gender                       3900 non-null   object
 3   item_purchased               3900 non-null   object
 4   category                     3900 non-null   object
 5   purchase_amount_(usd)        3900 non-null   int64
 6   location                     3900 non-null   object
 7   size                         3900 non-null   object
 8   color                        3900 non-null   object
 9   season                       3900 non-null   object
 10  review_rating                3900 non-null   float64
 11  subscription_status          3900 non-null   object
 12  shipping_type                3900 non-null   object
 13  discount_applied             3900 non-null   object
 14  previous_purchases           3900 non-null   int64
 15  payment_method               3900 non-null   object
 16  frequency_of_purchases       3900 non-null   object
 17  age_group                    3900 non-null   category
 18  frequency_of_purchases_days  3316 non-null   float64
dtypes: category(1), float64(2), int64(4), object(12)
memory usage: 552.6+ KB

In [39]:
df['frequency_of_purchases_days'] = df['frequency_of_purchases_days'].astype('Int64')

print(df['frequency_of_purchases_days'].dtype)

Int64

In [40]:

display(df.head(10))
df.info()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,frequency_of_purchases_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Mid Age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Mid Age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Adult,365
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Mid Age,7
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior Citizen,90
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Adult,7
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Adult,365
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Mid Age,90

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  3900 non-null   int64
 1   age                          3900 non-null   int64
 2   gender                       3900 non-null   object
 3   item_purchased               3900 non-null   object
 4   category                     3900 non-null   object
 5   purchase_amount_(usd)        3900 non-null   int64
 6   location                     3900 non-null   object
 7   size                         3900 non-null   object
 8   color                        3900 non-null   object
 9   season                       3900 non-null   object
 10  review_rating                3900 non-null   float64
 11  subscription_status          3900 non-null   object
 12  shipping_type                3900 non-null   object
 13  discount_applied             3900 non-null   object
 14  previous_purchases           3900 non-null   int64
 15  payment_method               3900 non-null   object
 16  frequency_of_purchases       3900 non-null   object
 17  age_group                    3900 non-null   category
 18  frequency_of_purchases_days  3316 non-null   Int64
dtypes: Int64(1), category(1), float64(1), int64(4), object(12)
memory usage: 556.4+ KB

In [41]:
df = df.drop(columns=['frequency_of_purchases'])

In [42]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,age_group,frequency_of_purchases_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Mid Age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Mid Age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Adult,365
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Mid Age,7
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Senior Citizen,90
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Adult,7
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Adult,365
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Mid Age,90

In [43]:
%pip install sqlalchemy pymysql pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in /Users/madhusreekalluri/Library/Python/3.9/lib/python/site-packages (2.0.48)
Requirement already satisfied: pymysql in /Users/madhusreekalluri/Library/Python/3.9/lib/python/site-packages (1.1.2)
Requirement already satisfied: pandas in /Users/madhusreekalluri/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/madhusreekalluri/Library/Python/3.9/lib/python/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.22.4 in /Users/madhusreekalluri/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/madhusreekalluri/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/madhusreekalluri/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/madhusreekalluri/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [48]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine, text
import urllib.parse

user = "root"
password = "Madhusree@20"
host = "localhost"
port = "3306"
db_name = "customer_analysis"

safe_password = urllib.parse.quote_plus(password)
url = f"mysql+pymysql://{user}:{safe_password}@{host}:{port}"

try:
    engine = create_engine(url)
    with engine.connect() as conn:
        conn.execute(text(f"CREATE DATABASE IF NOT EXISTS {db_name}"))
        conn.execute(text("COMMIT"))
    
    db_url = f"{url}/{db_name}"
    db_engine = create_engine(db_url)
    
    df_sql = df.copy()
    for col in df_sql.columns:
        if str(df_sql[col].dtype) in ['category', 'Int64', 'object', 'category']:
            df_sql[col] = df_sql[col].astype(str)
            
    df_sql.to_sql('shopping_data', con=db_engine, if_exists='replace', index=False)
    print("DONE! Check your MySQL tab now.")
except NameError:
    print("Please click 'Run All' at the top of the page first!")
except Exception as e:
    print(e)

DONE! Check your MySQL tab now.